### ISSUE TITLE
feat: Improve current quantizer codebase

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/WhisperSpeech#5]
# Problem
- We init the code base for simple training. However, still need a lot to improve e.g. evaluation code, multi GPUs training, etc

# Goal
- Adding in codebase

# Task
- [x] Add evaluation code: [WER](https://github.com/huggingface/evaluate/blob/main/metrics/wer/wer.py), [CER](https://github.com/huggingface/evaluate/blob/55f1bc6e072b05c2d9db1589a07e20f38902b1ec/metrics/cer/cer.py#L119)
- [x] Multi GPUs training
- [x] Add inference/ testing
- [x] Add logging when training (CE loss, KL loss, VQ loss)
- [x] Check data batch flow x iterations 
- [x] Add cosine lr w/ linear scheduler warmup
- [x] Add checkpoint log and resume (compatible)
- [x] Fix H100 bug: H100 doesn't compatible with `torchlightning`
- [x] Add `README.md`

**Comment by hahuyhoang411** [comment]
Done as 
<img width="1252" alt="Screenshot 2024-12-02 at 07 38 17" src="https://github.com/user-attachments/assets/5a21fe7f-f98d-4413-ac7f-c95fe94da463">
